language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --no-default-features
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
      cargo bench --verbose;
    fi

notifications:
  email: false
